### ISSUE TITLE
不知有意加入汉语方言各音不？

### ISSUE THREAD

**Issue by jinntrance** [MaigoAkisame/MCPDict#1]

**Comment by Kahaani** [comment]
恭喜！一年多之后新增了上海话和闽南话。

关于潮州话，在线字音资源有：
- [潮语研习网](http://www.teochewdialect.net)
- [潮州母语](http://www.mogher.com)
- [潮州音字典](http://www.czyzd.com)
- [潮州音](http://www.chaozhouyin.com)
- [潮语拼音输入法](https://github.com/Kahaani/dieghv)（公开的码表相当于字音对照）

拼音方案有：
- [省教潮拼](http://www.teochewdialect.net/phonology.php?code=)
- [现代潮罗](http://www.ispeakmin.com/bbs/viewthread.php?tid=2784)
- [家己人拼音](http://www.gaginang.org/language/pengim-guide)
- [潮语拼音](http://kahaani.github.io/gatian/appendix1/dieziu.html)

但是已经有闽南话作为闽语的代表了。

**Comment by MaigoAkisame** [comment]
好的，等我有空时研究一下。

**Comment by kunki** [comment]
http://xiaoxue.iis.sinica.edu.tw/ccr
小学堂的“漢字古今音資料庫”有比较完备的上古、中古音、现代方言的资料。
我撷取了一部分离线使用。
