### ISSUE TITLE
希望可以記憶“查詢模式”

### ISSUE THREAD

**Issue by yanrs17** [MaigoAkisame/MCPDict#10]
我從來都是用“普通話”（拼音）來查字的，但每次要用的時候，他就會改回默認的“漢字”查詢模式。就是每次用都得專門調一下那個“查詢模式”選擇“普通話”，特別費勁，如果能夠保留用戶習慣，每次開應用的時候可以保留上次用戶選定的“查詢模式”就更好了（對我來說就是“普通話”）。謝謝！

如果應用原本就是開的，但只是切換到另外一個應用，再切換回來，就沒有這個問題。就是把應用完全關了再打開的時候，“查詢模式”就又變成默認值“漢字”了，我就又需要再調到“普通話”，如果能改進當然是最好的，謝謝！

**Comment by MaigoAkisame** [comment]
好的~这个比较容易，把查询模式跟另外三个选项一样持久化就可以了。
