### ISSUE TITLE
What's the open source license for this project?

### ISSUE THREAD

**Issue by nlpguyz** [MaigoAkisame/MCPDict#11]
My colleagues want to contribute but are not sure what the result will be.

**Comment by MaigoAkisame** [comment]
Actually I haven't studied the types of licenses...
What are the contributions you're considering?

**Comment by nlpguyz** [comment]
I want to add some dialect data and use the search functionality to study them.

**Comment by MaigoAkisame** [comment]
What are the dialects, and where does the data come from?
Can I take a look at the data?

**Comment by nlpguyz** [comment]
Some northern dialects from online buddies. I don't have the data yet.

**Comment by MaigoAkisame** [comment]
Let me know when you have the data :)

**Comment by glixlur** [comment]
@MaigoAkisame Would you consider adding a license to this project? I’m using it in a project that includes your work.

**Comment by MaigoAkisame** [comment]
@glixlur I just added the MIT license :)
