### ISSUE TITLE
What is the data source for Kan'on?

### ISSUE THREAD

**Issue by sgalal** [MaigoAkisame/MCPDict#12]
我發現漢音數據有許多可疑之處，如「禺」有「ギョウ」的讀音。

**Comment by MaigoAkisame** [comment]
日语读音来自《汉字源》第五版。刚刚查了一下，上面说「禺禺」（ギョウギョウ・グウグウ）为鱼名。

**Comment by sgalal** [comment]
關於「禺」字，我在網絡上找不到「禺禺」（ギョウギョウ・グウグウ）這個詞，而且也不能確定「ギョウ」的讀音就是漢音。不過既然原書這麼寫，我提議可以將詞典的數據來源寫在 README 中。

**Comment by MaigoAkisame** [comment]
数据的来源在应用内的帮助页面有写哈。
