### ISSUE TITLE
關於搜索功能的一點建議

### ISSUE THREAD

**Issue by ThomasHawaiiKing** [MaigoAkisame/MCPDict#2]
可否加入簡單的通配符、甚至正則表達式的搜索支持？有時候想根據羅馬字搜索一堆相關的字時十分不便（實驗貌似只有聲母*這種格式可以用）

**Comment by MaigoAkisame** [comment]
现在的搜索是基于SQLite的全文搜索功能，我还没有研究过它对通配符的支持如何。

我将来可以探索一下，不过不保证效果。

**Comment by MaigoAkisame** [comment]
能举一些你希望使用通配符的例子吗？

按照字音检索，如果使用通配符，往往结果会很多，浏览起来恐怕也会有不便……

**Comment by ThomasHawaiiKing** [comment]
例如我家方言部分日母字變爲以[i]開頭的發音，我想看看所有日母字（或者日母與特定韻腹相拼）都有哪些，我可以搜索nj*或者nja*這樣，經過實驗是可行的（然而其他的例如zs*會出現類似zsr*這類並不想要的字）；同時我還想看類似特定聲母、入聲韻尾（例如nj*t），但這是暫時無法搜索的。諸如此類~

**Comment by MaigoAkisame** [comment]
刚刚查了一下SQLite全文搜索的文档，它仅支持精确匹配和前缀匹配。前缀匹配指的是你用“zs*”作关键字，可以搜出所有以zs开头的词（当然也包括以zsr、zsj开头的）。

如果要支持更复杂的通配符（甚至正则表达式），就不能利用SQLite的全文搜索功能了，对于我的实现是个挑战。另一方面，如果真要达到“搜索邪母字，但排除俟母、船母字”的目的，需要写的正则表达式也比较复杂，一般用户难以掌握，在手机上输入也并不方便。

所以我不准备支持通配符和正则表达式了。如果你需要按声母搜索，其实最好的方法是使用poem整理的广韵字音表（Excel格式，可以在这里下载：https://zhuanlan.zhihu.com/p/20430939）。
