### ISSUE TITLE
 Sqlite 中的 mcpdict 和 mcpdict_content 两表有何区别

### ISSUE THREAD

**Issue by brazeel** [MaigoAkisame/MCPDict#6]
打开 mcpdict.db 这一文件后。发现里面有四个表。其中 mcpdict 和 mcpdict_content 打开之后我未发现有何区别，除了后者有一个 id 作为主键。请问这个是设计成这样的。还是只是用工具生成 sqlite 文件的副产物。

**Comment by MaigoAkisame** [comment]
是工具的副产物。

我使用了 SQLite FTS 来做全文检索，mcpdict_content 是 FTS 生成的「shadow tables」之一。

详见：https://www.sqlite.org/fts3.html

**Comment by brazeel** [comment]
Thanks
