### ISSUE TITLE
請問有增加字數或其他方言讀音的計劃吗？

### ISSUE THREAD

**Issue by osfans** [MaigoAkisame/MCPDict#7]
有的话，我就提PR了。

unicode 10也發佈了，支持越來越多的漢字了。
開源的方言讀音。

**Comment by MaigoAkisame** [comment]
其它方言现在有考虑的是老国音、苏州话和客家话。
增加字数暂时还没有考虑，因为增加的生僻字很多没有配套的字音数据。

**Comment by jacob-us** [comment]
支持添加老國音。
也可以優化下注音的標法，應用裏的一些標法是不對的，可以趁機一道改下。

**Comment by MaigoAkisame** [comment]
注音具体是哪里不对呢？

**Comment by jacob-us** [comment]
目前查詢軟件「整體認讀」音節有兩種標示法:
1.ㄓㄔㄕㄖㄗㄘㄙ
2.ㄓㄧㄔㄧㄕㄧㄖㄧㄗㄧㄘㄧㄙㄧ
兩種均能在注音查詢模式查出所需字，但從注音設計之初的角度，只有第一種才正確。

**Comment by MaigoAkisame** [comment]
谢谢！这的确是个bug，下一个版本会修正。

**Comment by osfans** [comment]
@MaigoAkisame 
我現在有江淮官話的泰如字典：http://taerv.nguyoeh.com/zidian/

**Comment by MaigoAkisame** [comment]
@osfans 你好！我的app并没有计划收录分片这么细致的方言，暂时就不收啦~

**Comment by osfans** [comment]
那我就要fork自己修改添加然後發佈，授權吧？哈哈。

**Comment by osfans** [comment]
那上海話跟蘇州話要兩個都收嗎？

**Comment by MaigoAkisame** [comment]
苏州话将来会收，但不会再收别的吴语了。
你可以制作一个查询泰如话的app，不过我并没有计划把它合并进来。

**Comment by osfans** [comment]
瞭解。
閩南語這邊有：
https://github.com/a-thok/rime-hokkien
