### ISSUE TITLE
使用Objective-C实现的iOS版本

### ISSUE THREAD

**Issue by Umiiii** [MaigoAkisame/MCPDict#8]
![](https://github.com/Umiiii/MCPDict-iOS/blob/master/Preview.gif?raw=true)
我看第一个issue的作者貌似弃坑了，然后Swift又更了新版本，所以我用OC又写了个，现在界面大体上已经完成了，半年之内可能我会陆续填坑。另外作者能接受上架 App Store 收费 1元 或 6元 吗？因为开发者账号不便宜，我想让更多的人用到，在营销额达到开发者账号的成本之后后我会换成免费的，当然源代码会一直开放，不想买也可以自己编译。

P.S： 作者说的把函数框架留着实现你来现在还有效吗？哈哈，因为有些 Java 代码我没搞懂。

**Comment by MaigoAkisame** [comment]
看起来不错呀！

收费没问题。Orthography的部分我可以帮着写。
