### ISSUE TITLE
聲調不敏感？

### ISSUE THREAD

**Issue by yanrs17** [MaigoAkisame/MCPDict#9]
僅僅只是一個建議。拼音查字的時候，如果拼音沒有標聲調，就按照“聲調不敏感”，不然有時候忘記調了，他總是說“未找到符合條件的漢字”，每次都要勾上“聲調不敏感”，有點煩。只是不知道這樣會影響到其他哪些部分？如果有什麼我沒想到的負面影響就算了，謝謝！

**Comment by MaigoAkisame** [comment]
嗯，我自己用的时候也发现了这个问题。我可以在下个版本中考虑一下。
与它冲突的需求应该只有「只想查轻声字」的时候，此时可以用加个0代表声调的方法解决。

**Comment by yanrs17** [comment]
謝謝大佬這麼快就回覆，不勝感激！
